version: '3.8'

services:
  ollama:
    image: ollama/ollama:rocm
    environment:
      - 'HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION}'
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
